### ISSUE TITLE
WeakReference is not weak in JavaScript

### ISSUE THREAD

**Issue by yelbota** [tenderowls/moorka#22]
Epic fail. What should I do?

    val a = Var("")
    val b = Var("")
    val c = Var("")

    val g = a flatMap { a => 
      b flatMap { b => // This
        c map { c => // And this. Will leak on every update of g binding
          a + b + c
        }
      }
    }

**Comment by Lovesan** [comment]
Учитывая, что циклов в графе у нас быть не может, строго говоря, можно попробовать Reference Counting, как в COM, или там как в Python старом, или как в умных указателях в C++

**Comment by yelbota** [comment]
@Lovesan  Speak english please. This is a public repo.
Ok. How you should implement reference counting in Scala?

**Comment by yelbota** [comment]
Solution

    val g = reaper mark {
      a flatMap { a => 
        b flatMap { b => 
          c flatMap { c =>
            a + b + c
          }
        }
      }
    }

On every run kill dependent binding which is not marked by reaper.
