### ISSUE TITLE
Moorka UI redesign

### ISSUE THREAD

**Issue by fomkin** [tenderowls/moorka#35]
It will be new module and package Felix. So that are we need
* Dynamic typed template engine (no predefined tags)
* No Scala.js dependencies
* No global objects

It will fix #8 #9 

That else?
- [x] RxElement (switch?)
- [x] FutureElement
- [x] Tests for PropertyDirective

**Comment by yelbota** [comment]
I'v decide to move "React-like virtual-dom with diff applying" to backlog.

**Comment by fomkin** [comment]
Issue became EPIC!

**Comment by fomkin** [comment]
That else?
[ ] RxElement (switch?)
[ ] FutureElement
[ ] Tests for PropertyDirective
