### ISSUE TITLE
Vaska.worker use wrong quotes in importScripts

### ISSUE THREAD

**Issue by LMnet** [tenderowls/moorka#74]

**Comment by fomkin** [comment]
What do you mean?

**Comment by LMnet** [comment]
Just take a look at the pull request:  https://github.com/tenderowls/moorka/pull/75

**Comment by fomkin** [comment]
What kind of problem it fix?

**Comment by LMnet** [comment]
Old version of the code had wrong quotes. It produced  wrong `importScript` statement. It leads to error in `Vaska.worker` method with dependencies, like this:
`Vaska.worker("my.Main", "../client-fastopt.js", "../client-jsdeps.js");`
